new initd scripts and sysconfig files

diff --git a/debian/rmmaster.init b/debian/rmmaster.init
--- a/debian/rmmaster.init
+++ b/debian/rmmaster.init
@@ -1,258 +1,127 @@
-#!/bin/sh
+#! /bin/sh
 #
-# rmmaster         Start/Stop rmmaster
+#/******************************************************************************
+#                      rmmaster.init
+#
+# This file is part of the Castor project.
+# See http://castor.web.cern.ch/castor
+#
+# Copyright (C) 2003  CERN
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
+#
+# @(#)$RCSfile: rmmaster.init,v $ $Revision: 1.5 $ $Release$ $Date: 2007/06/28 11:23:53 $ $Author: waldron $
 #
 # chkconfig: 345 72 33
-# description: RMMASTER (Node Resource Monitoring Master Daemon)
+# description: Resource Monitoring Master Daemon Initialisation Script
+# note: purely used to submit LSF jobs
 #
-# $Id: rmmaster.init,v 1.4 2006/10/25 13:30:03 sponcec3 Exp $
-#
-# @(#)$RCSfile: rmmaster.init,v $ $Revision: 1.4 $ $Date: 2006/10/25 13:30:03 $ CERN/IT/ADC/CA Vitaly Motyakov
-#
+# @author castor dev team
+#*****************************************************************************/
 
-sysname=`uname -s`
+# Source function library.
+. /etc/rc.d/init.d/functions
 
-# source function library
-if [ -r /etc/rc.d/init.d/functions ]; then
-	. /etc/rc.d/init.d/functions
-	DAEMON=daemon
-	FAILURE=failure
-	ECHO_FAILURE=failure
-	SUCCESS=success
-	ECHO_SUCCESS=echo_success
-	ECHO_END=echo
-	if [ $sysname = "Linux" ]; then
-		ECHOOPT=-n
-	fi
-else
-	DAEMON=
-	FAILURE=
-	ECHO_FAILURE=
-	SUCCESS=
-	ECHO_SUCCESS=
-	ECHOOPT=
-	ECHO_END=
-fi
-
-RETVAL=0
+# Variables
 prog="rmmaster"
-NOMORERMMASTER=/var/run/nomorermmaster
-PIDFILE=/var/run/rmmaster.pid
-PIDDIR=/var/run
-SUBSYS=/var/lock/subsys/rmmaster
-SUBSYSDIR=/var/lock/subsys
-[ -z "$SILENTSTOP" ] && SILENTSTOP=0
-RMMASTER=/usr/bin/rmmaster
-# not yet supported
-RMMASTERLOGFILE=/var/log/rmmaster
-SYSCONFIGRMMASTER=/etc/sysconfig/rmmaster
+RETVAL=0
 
-#
-## Blindly attempt to create useful directories
-#
-[ ! -d $PIDDIR ] && mkdir -p $PIDDIR >& /dev/null
-[ ! -d $SUBSYSDIR ] && mkdir -p $SUBSYSDIR >& /dev/null
-
-if [ $sysname = "HP-UX" ]; then
-	export UNIX95=1
+# Source sysconfig files
+if [ -f /etc/sysconfig/castor ]; then
+	. /etc/sysconfig/castor
 fi
-if [ $sysname = "SunOS" ]; then
-	format4comm="fname"
-else
-	format4comm="comm"
+if [ -f /etc/sysconfig/$prog ]; then
+	. /etc/sysconfig/$prog
 fi
 
-#
-## Unless sysconfig says no the default is to run the server
-#
-RUN_RMMASTER=yes
+start() {
+	# run daemon
+	echo -n $"Starting $prog: "
 
+	# process sysconfig settings
+	if [ -f /etc/sysconfig/$prog ]; then
+
+		# enabled ?	    
+		if [ "${RMMASTER_RUN}" != "YES" ]; then
+			echo -n $"$prog disabled in /etc/sysconfig/$prog" 
+			failure && echo && exit
+		fi
+	fi
+
+        # check if daemon is already running
+        if [ -e /var/lock/subsys/$prog ]; then
+                if [ -n "`/sbin/pidof $prog`" ]; then
+                        echo -n $"already running"
+                        failure
+                        echo
+                        return 1
+                fi
+        fi
+
+	# disable internal retries
+	export STAGE_NORETRY=1
+	export STAGE_CONNTIMEOUT=3
+	export STAGE_TIMEOUT=3
+	export RFIO_CONNTIMEOUT=3
+	export RFIO_RETRY=1
+	export RFIO_RETRYINT=1
+
+	daemon /usr/bin/$prog $RMMASTER_OPTIONS
+	
+	RETVAL=$?
+	[ $RETVAL -eq 0 ] && success $"$base startup" || failure $"$base startup"
+	echo
+	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
+	return $RETVAL
+}
+
+stop() {
+	echo -n $"Stopping $prog: "
+	killproc $prog
+	
+	RETVAL=$?
+	echo
+	[ -f /var/lock/subsys/$prog ] && rm -f /var/lock/subsys/$prog
+	[ -f /var/run/$prog.pid ] && rm -f /var/run/$prog.pid
+	return $RETVAL	
+}
+
+restart() {
+	stop
+        start 
+}
+
+# See how we were called
 case "$1" in
-  start)
-	#
-	## rmmaster will use RFIO and STAGE api
-	#
-	## We make sure it does not fit into internal retries
-	#
-	STAGE_NORETRY=1
-	export STAGE_NORETRY
-	STAGE_CONNTIMEOUT=3
-	export STAGE_CONNTIMEOUT
-	STAGE_TIMEOUT=3
-	export STAGE_TIMEOUT
-	RFIO_CONNTIMEOUT=3
-	export RFIO_CONNTIMEOUT
-	RFIO_RETRY=1
-	export RFIO_RETRY
-	RFIO_RETRYINT=1
-	export RFIO_RETRYINT
-	echo $ECHOOPT "Starting $prog: "
-	if [ -f ${NOMORERMMASTER} ]; then
-        echo $ECHOOPT "${NOMORERMMASTER} exists: "
-		[ -n "$FAILURE" ] && $FAILURE "${NOMORERMMASTER} exists: "
-		RETVAL=1
-	else
-		ps -eo ppid,$format4comm | egrep '^[ \t]+1 rmmaster' > /dev/null
-		if [ $? -eq 0 ]; then
-			echo $ECHOOPT "rmmaster already started: "
-			[ -n "$FAILURE" ] && $FAILURE "rmmaster already started: "
-			RETVAL=1
-		else
-            if [ -r $SYSCONFIGRMMASTER ]; then
-                #
-                ## Source the configuration
-                #
-                . $SYSCONFIGRMMASTER
-                if [ "${RUN_RMMASTER}" != "yes" ]; then
-                    echo $ECHOOPT "$SYSCONFIGRMMASTER says NO: "
-                    [ -n "$FAILURE" ] && $FAILURE "$SYSCONFIGRMMASTER says NO: "
-                    RETVAL=1
-                fi
-                if [ -n "${ULIMIT_N}" ]; then
-                    ulimit -n ${ULIMIT_N}
-                fi
-                if [ -n "${ULIMIT_C}" ]; then
-                    ulimit -c ${ULIMIT_C}
-                fi
-            fi
-            if [ $RETVAL -eq 0 ]; then
-                #
-                ## Because we might generate a core file
-                ## We explicitely chdir in the workdir
-                #
-                cd /var/spool/rmmaster
-                $DAEMON $RMMASTER $OPTIONS
-                if [ $? -eq 0 ]; then
-                    [ -d $SUBSYSDIR ] && touch $SUBSYS
-		    if [ -d $PIDDIR ]; then
-			pid=`ps -eo pid,ppid,$format4comm | egrep " 1 rmmaster\$" | awk '{print $1}'`
-                        # The point of $PIDFILE is that it kills only
-                        # the master daemon.
-			rm -f $PIDFILE
-			if [ -n "$pid" ]; then
-			    echo $pid > $PIDFILE
-			    RETVAL=0
-			else
-			    echo $ECHOOPT "rmmaster not started: "
-			    [ -n "$FAILURE" ] && $FAILURE "rmmaster not started: "
-			    RETVAL=1
-			fi
-		    else
-			RETVAL=0
-		    fi
-                else
-                    echo $ECHOOPT "rmmaster not started: "
-                    [ -n "$FAILURE" ] && $FAILURE "rmmaster not started: "
-                    RETVAL=1
-                fi
-            fi
-        fi
-	fi
-	$ECHO_END
-	;;
-  stop)
-	if [ -f $PIDFILE ]; then
-		[ $SILENTSTOP -eq 0 ] && echo $ECHOOPT "Stopping $prog: "
-        if [ $SILENTSTOP -eq 0 ]; then
-		    kill -2 -`cat $PIDFILE`
-        else
-	        kill -2 -`cat $PIDFILE` >& /dev/null
-        fi
-        RETVAL=$?
-        if [ $RETVAL -eq 0 ]; then
-            rm -f $PIDFILE
-        fi
-	else
-		# rmmaster might have been started by hand
-		pid=`ps -eo pid,ppid,$format4comm | egrep " 1 rmmaster\$" | awk '{print $1}'`
-		if [ -n "$pid" ]; then
-			[ $SILENTSTOP -eq 0 ] && echo $ECHOOPT "Stopping $prog: "
-            if [ $SILENTSTOP -eq 0 ]; then
-                kill -2 -$pid
-            else
-                kill -2 -$pid >& /dev/null
-            fi
-            RETVAL=$?
-		else
-			[ $SILENTSTOP -eq 0 ] && echo $ECHOOPT "rmmaster already stopped: "
-			[ $SILENTSTOP -eq 0 -a -n "$FAILURE" ] && $FAILURE "rmmaster already stopped: "
- 			RETVAL=1
-		fi
-	fi
-	if [ $SILENTSTOP -eq 0 -a $sysname = "Linux" ]; then
-		if [ $RETVAL -eq 0 ]; then
- 			$ECHO_SUCCESS
-		else
- 			$ECHO_FAILURE
-		fi
-	fi
-	[ -d $SUBSYSDIR ] && rm -f $SUBSYS
-	[ $SILENTSTOP -eq 0 -a -n "$ECHO_END" ] && $ECHO_END
-    #
-    ## Basically: if SILENTSTOP is not 0 when we never print something
-    ## But if the stop is successful... One might want to see stop: OK
-    ## anyway ?
-    #
-	if [ $SILENTSTOP -ne 0 -a $RETVAL -eq 0 ]; then
-        echo $ECHOOPT "Stopping $prog: "
-        [ $sysname = "Linux" ] && $ECHO_SUCCESS
-        [ -n "$ECHO_END" ] && $ECHO_END
-    fi
-	;;
-  restart)
-	$0 stop
-	if [ $? -eq 0 -o $SILENTSTOP -eq 0 ]; then
-		# We have to wait a bit so that the former rmmaster exits
-		sleep 10
-		$0 start
+	
+	start)
+		start
+		;;
+	stop)
+		stop
+		;;
+	status)
+		status $prog
 		RETVAL=$?
-	else
-        #
-        ## It is legal to return zero it if was
-        ## a conditional restart
-        #
-        if [ $SILENTSTOP -eq 0 ]; then
-            RETVAL=1
-        else
-            RETVAL=0
-        fi
-	fi
-	;;
-  condrestart)
-	SILENTSTOP=1
-    export SILENTSTOP
-	$0 restart
-    RETVAL=$?
-	;;
-  status)
-	pid=`ps -eo pid,ppid,$format4comm | egrep " 1 rmmaster\$" | awk '{print $1}'`
-	if [ -n "$pid" ]; then
-		echo $ECHOOPT "rmmaster (pid $pid) is running..."
-		$ECHO_SUCCESS
-		$ECHO_END
-	else
-		if [ -f $PIDFILE ]; then
-			pid=`head -1 $PIDFILE`
-			if [ "$pid" != "" ] ; then
-				echo $ECHOOPT "rmmaster dead but pid file exists"
-				$ECHO_FAILURE
-				$ECHO_END
-			fi
-		else
-			if [ -f $SUBSYS ]; then
-				echo $ECHOOPT "rmmaster dead but subsys ($SUBSYS) locked"
-			else
-				echo $ECHOOPT "rmmaster is stopped"
-			fi
-			$ECHO_FAILURE
-			$ECHO_END
-		fi
-	fi
-	;;
-  *)
-	echo "Usage: $0 {start|stop|status|restart|condrestart}"
-	RETVAL=1
-	;;
+		;;
+	restart)
+		restart
+		;;
+	condrestart)
+		[ -f /var/lock/subsys/$prog ] && restart || :
+		;;
+	*)
+		echo $"Usage: $0 {start|stop|status|restart|condrestart}"
+		exit 1
 esac
 
 exit $RETVAL
