[log_analysis] Fixes floating point maths on sub-second timestamps

diff --git a/continuousintegration/log_analysis/tracefile b/continuousintegration/log_analysis/tracefile
--- a/continuousintegration/log_analysis/tracefile
+++ b/continuousintegration/log_analysis/tracefile
@@ -1,5 +1,19 @@
 #!/bin/sh
 
+error()
+{
+  echo "$*" >&2
+  exit 1
+}
+
+get_filename()
+{
+  awk -vFILENAME=${1} -vFILENAME_PREFIX=${FILENAME_PREFIX} 'BEGIN {
+    FILENAME="00000000" FILENAME
+    print FILENAME_PREFIX substr(FILENAME, length(FILENAME)-7)
+  }'
+}
+
 get_ids()
 {
   IDS=$(grep -m1 "^$1 " filenameToLogIds.txt)
@@ -17,18 +31,18 @@ check_results()
 
 get_mgm_times()
 {
-  TMP_RESULTS=$(grep -m7 "^$1 " xrdmgm-events.log)
+  TMP_RESULTS=$(grep -m6 "^$1 " xrdmgm-events.log)
 
-  echo -e "${TMP_RESULTS}" | check_results 7
+  echo -e "${TMP_RESULTS}" | check_results 6
   [ $? -ne 0 ] && TMP_RESULTS=$(grep "^$1 " xrdmgm-events.log)
 
-  TIME_CREATE=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 CRE" | cut -d' ' -f3)
-  TIME_ACOMMIT=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 ACO" | cut -d' ' -f3)
-  TIME_CLOSEW=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 CLO" | cut -d' ' -f3)
-  TIME_ARCHIVED=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 ARC" | cut -d' ' -f3)
-  TIME_PREPARE=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 PRE" | cut -d' ' -f3)
-  TIME_RCOMMIT=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 RCO" | cut -d' ' -f3)
-  TIME_RETRIEVED=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 RWC" | cut -d' ' -f3)
+  TIME_MGM_CREATE=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 CRE" | cut -d' ' -f3)
+  TIME_MGM_ACOMMIT=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 ACO" | cut -d' ' -f3)
+  TIME_MGM_CLOSEW=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 CLO" | cut -d' ' -f3)
+  TIME_MGM_ARCHIVED=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 ARC" | cut -d' ' -f3)
+  TIME_MGM_PREPARE=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 PRE" | cut -d' ' -f3)
+  TIME_MGM_RCOMMIT=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 RCO" | cut -d' ' -f3)
+  #TIME_MGM_RETRIEVED=$(echo -e "${TMP_RESULTS}" | grep -m1 "^$1 RWC" | cut -d' ' -f3)
 }
 
 get_frontend_times()
@@ -70,7 +84,7 @@ get_taped_times()
 
 get_offset_time()
 {
-  echo $(($2-$1))
+  echo "$2-$1" | bc -l
 }
 
 get_times()
@@ -82,19 +96,29 @@ get_times()
 
   echo -n "$ARCHIVE_ID $FILE_ID "
 
-  echo -n "$(get_offset_time $TIME_CREATE $TIME_FE_CREATE) "
-  echo -n "$(get_offset_time $TIME_FE_CREATE $TIME_ACOMMIT) "
-  echo -n "$(get_offset_time $TIME_ACOMMIT $TIME_CLOSEW) "
-  echo -n "$(get_offset_time $TIME_CLOSEW $TIME_FE_CLOSEW) "
+# For debugging
+#  echo $TIME_MGM_CREATE $TIME_FE_CREATE $TIME_MGM_ACOMMIT $TIME_MGM_CLOSEW $TIME_FE_CLOSEW $TIME_TS_ARCHIVE_POP \
+#       $TIME_TS_ARCHIVE_TASKS $TIME_TS_ARCHIVE_OPEN $TIME_TS_ARCHIVE_READ $TIME_TS_ARCHIVE_DONE $TIME_TS_ARCHIVE_REPORT \
+#       $TIME_MGM_ARCHIVED
+#  echo $TIME_MGM_PREPARE $TIME_FE_PREPARE $TIME_TS_RETRIEVE_POP $TIME_TS_RETRIEVE_TASK $TIME_TS_RETRIEVE_TASKS \
+#       $TIME_TS_RETRIEVE_POSITION $TIME_TS_RETRIEVE_READ $TIME_TS_RETRIEVE_OPEN $TIME_TS_RETRIEVE_DONE \
+#       $TIME_MGM_RCOMMIT $TIME_MGM_RETRIEVED
+
+  # MGM events have second precision. CTA events have microsecond precision
+
+  echo -n "$(get_offset_time $TIME_MGM_CREATE $TIME_FE_CREATE) "
+  echo -n "$(get_offset_time $TIME_MGM_CREATE $TIME_MGM_ACOMMIT) "
+  echo -n "$(get_offset_time $TIME_MGM_ACOMMIT $TIME_MGM_CLOSEW) "
+  echo -n "$(get_offset_time $TIME_FE_CREATE $TIME_FE_CLOSEW) "
   echo -n "$(get_offset_time $TIME_FE_CLOSEW $TIME_TS_ARCHIVE_POP) "
   echo -n "$(get_offset_time $TIME_TS_ARCHIVE_POP $TIME_TS_ARCHIVE_TASKS) "
   echo -n "$(get_offset_time $TIME_TS_ARCHIVE_TASKS $TIME_TS_ARCHIVE_OPEN) "
   echo -n "$(get_offset_time $TIME_TS_ARCHIVE_OPEN $TIME_TS_ARCHIVE_READ) "
   echo -n "$(get_offset_time $TIME_TS_ARCHIVE_READ $TIME_TS_ARCHIVE_DONE) "
   echo -n "$(get_offset_time $TIME_TS_ARCHIVE_DONE $TIME_TS_ARCHIVE_REPORT) "
-  echo -n "$(get_offset_time $TIME_TS_ARCHIVE_REPORT $TIME_ARCHIVED) "
+  echo -n "$(get_offset_time $TIME_TS_ARCHIVE_REPORT $TIME_MGM_ARCHIVED) "
 
-  echo -n "$(get_offset_time $TIME_PREPARE $TIME_FE_PREPARE) "
+  echo -n "$(get_offset_time $TIME_MGM_PREPARE $TIME_FE_PREPARE) "
   echo -n "$(get_offset_time $TIME_FE_PREPARE $TIME_TS_RETRIEVE_POP) "
   echo -n "$(get_offset_time $TIME_TS_RETRIEVE_POP $TIME_TS_RETRIEVE_TASK) "
   echo -n "$(get_offset_time $TIME_TS_RETRIEVE_TASK $TIME_TS_RETRIEVE_TASKS) "
@@ -102,19 +126,27 @@ get_times()
   echo -n "$(get_offset_time $TIME_TS_RETRIEVE_POSITION $TIME_TS_RETRIEVE_READ) "
   echo -n "$(get_offset_time $TIME_TS_RETRIEVE_READ $TIME_TS_RETRIEVE_OPEN) "
   echo -n "$(get_offset_time $TIME_TS_RETRIEVE_OPEN $TIME_TS_RETRIEVE_DONE) "
-  echo -n "$(get_offset_time $TIME_TS_RETRIEVE_DONE $TIME_RCOMMIT);"
-  echo    "$(get_offset_time $TIME_RCOMMIT $TIME_RETRIEVED);"
+  echo    "$(get_offset_time $TIME_TS_RETRIEVE_DONE $TIME_MGM_RCOMMIT);"
+#  echo -n "$(get_offset_time $TIME_TS_RETRIEVE_DONE $TIME_MGM_RCOMMIT) "
+#  echo    "$(get_offset_time $TIME_MGM_RCOMMIT $TIME_MGM_RETRIEVED);"
 }
 
-FILE_NUM_START=${1:-1}
-FILE_NUM_END=${2:-1000000}
+FILE_NUM_START=${1:-0}
+FILE_NUM_END=${2:-9099999}
+
+FILENAME_PREFIX=
+
+[ -r filenameToLogIds.txt ] || error "Can't open filenameToLogIds.txt"
+[ -r xrdmgm-events.log ] || error "Can't open xrdmgm-events.log"
+[ -r cta-frontend-events.log ] || error "Can't open cta-frontend-events.log"
+[ -r cta-taped-events.log ] || error "Can't open cta-taped-events.log"
 
 echo "cta_times = ["
 
 FILE_NUM=${FILE_NUM_START}
 while :
 do
-  get_times /eos/dev/userfiles/testdir/group_${FILE_NUM}
+  get_times ${FILE_NUM}
   FILE_NUM=$((${FILE_NUM}+1))
   [ $FILE_NUM -le $FILE_NUM_END ] || break
 done
