Major simplification/rewrite of the Imakfile infrastructure. Main lines are :   - creation of small libraries per component, all called libcastor<component> and all lower case named. Note some renaming in the existing names, like libcastorCommonOra -> libcastorcommonora   - suppression of libshift for internal use, preferring to use a restricted set of small libraries. libshift only exists now for backward compatibility reasons on the client side and does not contain any code, only dependencies to the new libraries   - creation of easy build targets, such as NormalProgramTarget, SharedLibraryTarget or EXEMANPAGE. Look at examples on how to use them   - proper enforcement of all Makefiles dependencies, using DependOnLibrary macro   - automation of a lot of nasty repetitive actions, e.g. looping on subdirectories for all Makefile standard targets   - dropped support for many outdated (to say the least) external tools. e.g. hpss, cray OS, dbana, ....

diff --git a/config/Project.tmpl b/config/Project.tmpl
--- a/config/Project.tmpl
+++ b/config/Project.tmpl
@@ -304,10 +304,6 @@
 #undef BuildVdqmLibrary
 #define BuildVdqmLibrary YES
 #endif
-#if !Accounting
-#undef Accounting
-#define Accounting YES
-#endif
 #if !BuildVolumeMgrLibrary
 #undef BuildVolumeMgrLibrary
 #define BuildVolumeMgrLibrary YES
@@ -736,5 +732,46 @@ GRIDFTPDIR = gridftp2
 
 /* Those directories are always defined because we always build at least */
 /* COMMON library */
-LIBDIR=lib
 SHLIBDIR=shlib
+
+.PHONY : all install clean clobber Makefiles depend checkDESTDIR
+
+all:
+
+checkDESTDIR:
+	@if [ "${DESTDIR}" == '' ]; \
+	then \
+	  echo "Please set DESTDIR environment variable before invoking make install."; \
+	  exit -1; \
+	fi
+
+install: checkDESTDIR all
+
+clean:
+	RemoveFiles($(FilesToClean))
+	GotoSubdirs($(SUBDIRS))
+
+clobber: clean
+	RemoveFiles($(FilesToClobber))
+	GotoSubdirs($(SUBDIRS))
+
+Makefiles:
+	@for i in $(SUBDIRS);\
+	do (if [ -d $$i ] ;\
+	    then \
+	      (echo " $$i:" ; cd $$i ;\
+	      $(CASTOR_ROOT)/imake/imake -I$(CASTOR_ROOT)/config;\
+	      $(MAKE) $(MFLAGS) $@) ;\
+	    else \
+	      (echo "ERROR : No directory $$i" ;\
+	      exit 1) ;\
+	    fi )\
+	done ;
+
+MakeSubdirs(all,$(SUBDIRS))
+MakeSubdirs(install,$(SUBDIRS))
+MakeSubdirs(exportman,$(SUBDIRS))
+
+depend:
+	makedepend $(INCLUDES) *.cpp *.hpp *.h 2> /dev/null
+	GotoSubdirs($(SUBDIRS))
