Imakefiles, spec and config files have been cleaned up and revisited. All dependencies are now properly handled and checks have been added for preventing compilation when missing dependencies are detected. Checked dependencies include oracle, stk, lsf, globus as well as the DESTDIR environment variable in case of make install. Build* targets in site.def are now obsolete. In order to compile a subpart of CASTOR, only regular make targets should be used. New targets "client", "tape", "installclient" and "installtape" have been created to compile/install the client/tape part only. This can be done even if dependencies are missing for the server side, e.g. the client compile and installs without oracle, lsf, stk.

diff --git a/config/Project.tmpl b/config/Project.tmpl
--- a/config/Project.tmpl
+++ b/config/Project.tmpl
@@ -3,744 +3,62 @@
  * All rights reserved
  */
 
-/*
- * @(#)$RCSfile$ $Revision$ $Date$ CERN IT-ADC/CA Jean-Damien Durand
- */
-
-/* ========================================== */
-/* Implicit dependencies because of libraries */
-/* ========================================== */
-
-/* --------------------------- */
-/* We force COMMON in any case */
-/* --------------------------- */
-#if !BuildCommon
-#undef BuildCommon
-#define BuildCommon YES
-#endif
-
-/* ---- */
-/* CUPV */
-/* ---- */
-#if BuildCupvClient || BuildCupvDaemon
-#if !BuildCupvLibrary
-#undef BuildCupvLibrary
-#define BuildCupvLibrary YES
-#endif
-#endif
-
-/* -------- */
-/* HSMTOOLS */
-/* -------- */
-#if BuildHsmTools
-#if !BuildNameServerLibrary
-#undef BuildNameServerLibrary
-#define BuildNameServerLibrary YES
-#endif
-#if !BuildRtcopyLibrary
-#undef BuildRtcopyLibrary
-#define BuildRtcopyLibrary YES
-#endif
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildVolumeMgrLibrary
-#undef BuildVolumeMgrLibrary
-#define BuildVolumeMgrLibrary YES
-#endif
-#if !BuildRfioClient
-#undef BuildRfioClient
-#define BuildRfioClient YES
-#endif
-#endif
-
-/* -- */
-/* NS */
-/* -- */
-#if BuildNameServerClient || BuildNameServerDaemon
-#if !BuildNameServerLibrary
-#undef BuildNameServerLibrary
-#define BuildNameServerLibrary YES
-#endif
-#endif
-
-/* ---- */
-/* RFIO */
-/* ---- */
-#if BuildRfioClient
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#endif
-
-/* --- */
-/* RMC */
-/* --- */
-#if BuildRmcClient
-#if !BuildRmcLibrary
-#undef BuildRmcLibrary
-#define BuildRmcLibrary YES
-#endif
-#endif
-#if BuildRmcServer
-#if !BuildRmcLibrary
-#undef BuildRmcLibrary
-#define BuildRmcLibrary YES
-#endif
-#if !BuildTapeLibrary
-#undef BuildTapeLibrary
-#define BuildTapeLibrary YES
-#endif
-#if !BuildCupvLibrary
-#undef BuildCupvLibrary
-#define BuildCupvLibrary YES
-#endif
-#endif
-
-/* --- */
-/* JOB */
-/* --- */
-#if BuildJob
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary	YES
-#endif
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#endif
-
-/* ------ */
-/* RTCOPY */
-/* ------ */
-#if BuildRtcopyClient
-#if !BuildRtcopyLibrary
-#undef BuildRtcopyLibrary
-#define BuildRtcopyLibrary YES
-#endif
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#if !BuildVolumeMgrLibrary
-#undef BuildVolumeMgrLibrary
-#define BuildVolumeMgrLibrary YES
-#endif
-#if BuildVdqmLibrary != YES
-#undef BuildVdqmLibrary
-#define BuildVdqmLibrary YES
-#endif
-#endif
-
-#if BuildRtcpclientd
-#if !BuildRtcopyLibrary
-#undef BuildRtcopyLibrary
-#define BuildRtcopyLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildExpertLibrary != YES
-#undef BuildExpertLibrary
-#define BuildExpertLibrary YES
-#endif
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#if !BuildVolumeMgrLibrary
-#undef BuildVolumeMgrLibrary
-#define BuildVolumeMgrLibrary YES
-#endif
-#if BuildVdqmLibrary != YES
-#undef BuildVdqmLibrary
-#define BuildVdqmLibrary YES
-#endif
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#endif
-
-#if BuildRtcopyServer
-#if !BuildRtcopyLibrary
-#undef BuildRtcopyLibrary
-#define BuildRtcopyLibrary YES
-#endif
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildVolumeMgrLibrary
-#undef BuildVolumeMgrLibrary
-#define BuildVolumeMgrLibrary YES
-#endif
-#if !BuildTapeLibrary
-#undef BuildTapeLibrary
-#define BuildTapeLibrary YES
-#endif
-#if BuildVdqmLibrary != YES
-#undef BuildVdqmLibrary
-#define BuildVdqmLibrary YES
-#endif
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#endif
-
-#if BuildRtstat
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#endif
-
-/* ------ */
-/* STAGER */
-/* ------ */
-#if BuildStageClient
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#endif
-
-#if BuildStageDaemon
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildCupvLibrary
-#undef BuildCupvLibrary
-#define BuildCupvLibrary YES
-#endif
-#if BuildExpertLibrary != YES
-#undef BuildExpertLibrary
-#define BuildExpertLibrary YES
-#endif
-#if BuildNameServerLibrary != YES
-#undef BuildNameServerLibrary
-#define BuildNameServerLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary	YES
-#endif
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#endif
-
-/* ---- */
-/* TAPE */
-/* ---- */
-#if BuildTapeDaemon
-#if !BuildTapeLibrary
-#undef BuildTapeLibrary
-#define BuildTapeLibrary YES
-#endif
-#if BuildRmcLibrary != YES
-#undef BuildRmcLibrary
-#define BuildRmcLibrary	YES
-#endif
-#if !BuildDlfLibrary
-#undef BuildDlfLibrary
-#define BuildDlfLibrary YES
-#endif
-#if !BuildVdqmLibrary
-#undef BuildVdqmLibrary
-#define BuildVdqmLibrary YES
-#endif
-#if !BuildVolumeMgrLibrary
-#undef BuildVolumeMgrLibrary
-#define BuildVolumeMgrLibrary YES
-#endif
-#endif
-
-#if BuildTapeClient
-#if !BuildTapeLibrary
-#undef BuildTapeLibrary
-#define BuildTapeLibrary YES
-#endif
-#if !BuildVolumeMgrLibrary
-#undef BuildVolumeMgrLibrary
-#define BuildVolumeMgrLibrary YES
-#endif
-#endif
-
-#if BuildTpusage
-#if BuildRfioLibrary != YES
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#endif
-
-/* ---- */
-/* TEST */
-/* ---- */
-/* TODO */
-
-/* ---- */
-/* VDQM */
-/* ---- */
-#if BuildVdqmClient
-#if !BuildVdqmLibrary
-#undef BuildVdqmLibrary
-#define BuildVdqmLibrary YES
-#endif
-#if !BuildRtcopyLibrary
-#undef BuildRtcopyLibrary
-#define BuildRtcopyLibrary YES
-#endif
-#if !BuildRfioLibrary
-#undef BuildRfioLibrary
-#define BuildRfioLibrary YES
-#endif
-#if !BuildVolumeMgrLibrary
-#undef BuildVolumeMgrLibrary
-#define BuildVolumeMgrLibrary YES
-#endif
-#endif
-
-/* ---- */
-/* VMGR */
-/* ---- */
-#if BuildVolumeMgrClient || BuildVolumeMgrDaemon
-#if !BuildVolumeMgrLibrary
-#undef BuildVolumeMgrLibrary
-#define BuildVolumeMgrLibrary YES
-#endif
-#endif
-
-/* ------ */
-/* EXPERT */
-/* ------ */
-#if BuildExpertClient || BuildExpertDaemon
-#if !BuildExpertLibrary
-#undef BuildExpertLibrary
-#define BuildExpertLibrary YES
-#endif
-#endif
-/* ---------------*/
-/* REQUEST HANDLER */
-/* --------------- */
-#if BuildRHCpp
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary	YES
-#endif
-#if !BuildNameServerLibrary
-#undef BuildNameServerLibrary
-#define BuildNameServerLibrary YES
-#endif
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#endif
-
-/* --------------- */
-/* New VDQM Server */
-/* --------------- */
-#if BuildVDQMCpp
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary YES
-#endif
-#endif
-
-/* ----------------- */
-/* New Repack        */
-/* ----------------- */
-#if BuildRepack
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary YES
-#endif
-#endif
-
-/* ----------------- */
-/* New MigHunter     */
-/* ----------------- */
-
-#if BuildMigHunterDaemon
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary YES
-#endif
-#if !BuildInfoPolicyLibrary
-#undef BuildInfoPolicyLibrary
-#define BuildInfoPolicyLibrary YES
-#endif
-#endif
-
-/* -------------------- */
-/* RecHandlerDaemon     */
-/* -------------------- */
-
-#if BuildRecHandlerDaemon
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary YES
-#endif
-#if !BuildInfoPolicyLibrary
-#undef BuildInfoPolicyLibrary
-#define BuildInfoPolicyLibrary YES
-#endif
-#endif
-
-/* ----------------- */
-/* InfoPolicy Lib    */
-/* ----------------- */
-#if BuildInfoPolicyLibrary
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary YES
-#endif
-#endif
-
-/* -------------------- */
-/* TapeGateway          */
-/* -------------------- */
-
-#if BuildTapeGatewayCpp
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary YES
-#endif
-#if !BuildInfoPolicyLibrary
-#undef BuildInfoPolicyLibrary
-#define BuildInfoPolicyLibrary YES
-#endif
-#endif
-
-/* ------------------ */
-/* Garbage Collection */
-/* ------------------ */
-#if BuildGCCpp
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary	YES
-#endif
-#endif
-
-/* ------------ */
-/* New RmMaster */
-/* ------------ */
-#if BuildRmMasterCpp
-#if !BuildStageLibrary
-#undef BuildStageLibrary
-#define BuildStageLibrary YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary	YES
-#endif
-#endif
-
-/******************/
-/* New JobManager */
-/******************/
-#if BuidlJobManagerCpp
-#if BuildDlfLibrary != YES
-#undef BuildDlfLibrary
-#define BuildDlfLibrary YES
-#endif
-#endif
-
-/* ------- */
-/* CPPTEST */
-/* ------- */
-#if BuildCppTest
-#if !BuildOraCpp && !BuildPgCpp && !BuildMyCpp
-#undef BuildOraCpp
-#define BuildOraCpp YES
-#endif
-#if !BuildCastorClientCPPLibrary
-#undef BuildCastorClientCPPLibrary
-#define BuildCastorClientCPPLibrary YES
-#endif
-#endif
-
-/* -------- */
-/* SECURITY */
-/* -------- */
-#if BuildSecurity
-#if BuildCommon != YES
-#undef BuildCommon
-#define BuildCommon     YES
-#endif
-#endif
-
-
-/* ======================= */
-/* For hidden dependencies */
-/* ======================= */
-#include <LibraryDeps.tmpl>
-
-/* ========================= */
-/* Directories for the build */
-/* ========================= */
-
-CLIENTSDIR = client
-#if BuildCommon
-COMMONDIR = common
-CNVCPPDIR = cnv
-#endif
-#if BuildCupvClient || BuildCupvDaemon || BuildCupvLibrary
-UPVDIR = upv
-#endif
-#if BuildHsmTools
-HSMTOOLSDIR = hsmtools
-#endif
-#if BuildNameServerClient || BuildNameServerDaemon || BuildNameServerLibrary
-NSDIR = ns
-#endif
-#if BuildRfioClient || BuildRfioServer || BuildRfioLibrary
-RFIODIR = rfio
-#endif
-#if BuildRmcClient || BuildRmcServer || BuildRmcLibrary
-RMCDIR = rmc
-#endif
-#if BuildJob
-JOBDIR = job
-STAGERJOBDIR = stagerjob
-#endif
-#if BuildRtcopyClient || BuildRtcopyServer || BuildRtcopyLibrary || BuildRtstat
-RTCOPYDIR = rtcopy
-#endif
-#if BuildStageDaemonCpp
-STAGERDIR = stager
-DAEMONDIR = daemon
-#endif
-#if BuildTapeClient || BuildTapeDaemon || BuildTapeLibrary || BuildTpusage
-TAPEDIR = tape
-#endif
-#if BuildVdqmClient || BuildVdqmLibrary
-VDQMDIR = vdqm
-#endif
-#if BuildVolumeMgrClient || BuildVolumeMgrDaemon || BuildVolumeMgrLibrary
-VMGRDIR = vmgr
-#endif
-#if BuildDlfDaemon || BuildDlfLibrary
-DLFDIR = dlf
-#endif
-#if BuildExpertClient || BuildExpertDaemon || BuildExpertLibrary
-EXPERTDIR = expert
-#endif
-#if BuildRHCpp
-RHCPPDIR = rh
-#endif
-#if BuildVDQMCpp
-VDQMCPPDIR = vdqm
-#endif
-#if BuildAggregatorCpp
-AGGREGATORCPPDIR = aggregator
-TAPECPPDIR = tape
-#endif
-#if BuildTapeFormatCpp
-TAPEFORMATCPPDIR = format
-TAPECPPDIR = tape
-#endif
-#if BuildRepack
-REPACKDIR = repack
-#endif
-#if BuildMigHunterDaemon
-MIGDIR = mighunter
-RTCOPYDIR = rtcopy
-#endif
-#if BuildRecHandlerDaemon
-RECDIR = rechandler
-RTCOPYDIR = rtcopy
-#endif
-#if BuildInfoPolicyLibrary
-INFOPOLICYDIR = infoPolicy
-#endif
-#if BuildTapeGatewayCpp
-TAPEGATEWAYCPPDIR = tapegateway
-TAPECPPDIR = tape
-#endif
-#if BuildGCCpp
-GCCPPDIR = gc
-#endif
-#if BuildCastorClientCPPLibrary || BuildRHCpp || BuildVDQMCpp || BuildGCCpp || BuildOraCpp || BuildPgCpp || BuildMyCpp || BuildStageDaemonCpp || BuildRmMasterCpp || BuildRmNodeCpp || BuildAggregatorCpp || BuildTapeFormatCpp
-COMMONCPPDIR = castor
-#endif
-#if BuildOraCpp
-ORACPPDIR = newora
-DBCPPDIR = db
-#endif
-#if BuildMyCpp
-MYCPPDIR = mysql
-DBCPPDIR = db
-#endif
-#if BuildPgCpp
-PGCPPDIR = pgsql
-DBCPPDIR = db
-#endif
-#if BuildCppTest
-COMMONCPPTESTDIR = castor
-DBTESTCPPDIR = db
-IOTESTCPPDIR = io
-DBCTESTCPPDIR = dbC
-STGSVCTESTCPPDIR = stgSvc
-MONITORINGTESTCPPDIR = monitoring
-#endif
-#if BuildSecurity
-SECURITYDIR=security
-#endif
-#if BuildSchedPlugin
-SCHEDULERDIR=scheduler
-#endif
-#if BuildDlfWeb
-DLFWEBDIR=web
 DLFWEB=/var/www/html/dlf
 DLFCONF=/var/www/conf/dlf
-#endif
-#if BuildRmMasterCpp
-MONITORINGDIR = monitoring
-RMMASTERDIR = rmmaster
-RMADMINDIR = admin
-#endif
-#if BuildRmNodeCpp
-MONITORINGDIR = monitoring
-RMNODEDIR = rmnode
-#endif
-#if BuildJobManagerCpp
-JOBMANAGERDIR = jobmanager
-DISKCOPYDIR = diskcopy
-#endif
-#if BuildGridFTP
-GRIDFTPDIR = gridftp2
-#endif
 
-/* Those directories are always defined because we always build at least */
-/* COMMON library */
-SHLIBDIR=shlib
+.PHONY : install clean clobber Makefiles depend checkDESTDIR checkORACLE checkLSF checkGLOBUS checkSTK
 
-.PHONY : all install clean clobber Makefiles depend checkDESTDIR
-
-all:
+all: checkORACLE checkLSF checkGLOBUS checkSTK
 	GotoSubdirs($(SUBDIRS))
 
 checkDESTDIR:
-	@if [ "${DESTDIR}" == '' ]; \
-	then \
+	@if [ -z "${DESTDIR}" ]; then \
 	  echo "Please set DESTDIR environment variable before invoking make install."; \
+	  exit -1; \
+	fi; \
+	if [ -z "${EXPORTMAN}" ]; then \
+          EXPORTMAN=$(DESTDIR)/usr/share/man; \
+        fi
+
+checkORACLE:
+	@if [ -z "${ORACLE_HOME}" ]; then \
+	  if [ -r /etc/sysconfig/castor ]; then /etc/sysconfig/castor; fi \
+	fi; \
+        if [ -z ${ORACLE_HOME} ]; then \
+	  echo "Please define ORACLE_HOME environment variable before invoking make."; \
+	  exit -1; \
+	fi; \
+	if [ ! -r ${ORACLE_HOME}/lib/libclntsh.so ]; then \
+	  echo "Could not find libclntsh.so in ${ORACLE_HOME}/lib. Giving up."; \
 	  exit -1; \
 	fi
 
-install: checkDESTDIR all
+checkLSF:
+	@if [ ! -e InstallLibDir/liblsf.so -o ! -d /usr/include/lsf ]; then \
+	  echo "Could not find LSF installation. Giving up."; \
+	  exit -1; \
+	fi
+
+checkGLOBUS:
+	@if [ -z "${GLOBUS_LOCATION}" ]; then GLOBUS_LOCATION="/opt/globus"; fi; \
+	if [ ! -r ${GLOBUS_LOCATION}/lib/libglobus_ftp_control_/**/GlobusFlavour.so -o ! -d ${GLOBUS_LOCATION}/include ]; then \
+	  echo "Could not find Globus installation. Giving up."; \
+	  exit -1; \
+	fi
+
+checkSTK:
+	@if [ ! -z "${CASTOR_NOSTK}" ]; then \
+	  echo "Compiling without STK support."; \
+	else \
+	  rpm -q stk-ssi-devel >&/dev/null && rpm -q stk-ssi >& /dev/null; \
+	  if [[ $$? -ne 0 ]]; then \
+	    echo "Could not find STK packages. Giving up."; \
+	    exit -1; \
+          fi; \
+	fi
+
+install: checkDESTDIR all exportman
+	GotoSubdirs($(SUBDIRS))
 
 clean:
 	RemoveFiles($(FilesToClean))
@@ -763,12 +81,9 @@ Makefiles:
 	    fi )\
 	done ;
 
-install:
-	GotoSubdirs($(SUBDIRS))
-
 exportman:
 	GotoSubdirs($(SUBDIRS))
 
 depend:
-	makedepend $(INCLUDES) *.cpp *.hpp *.h 2> /dev/null
+	makedepend -I $(CASTOR_ROOT) -I $(CASTOR_ROOT)/h *.c *.cpp *.hpp *.h 2> /dev/null
 	GotoSubdirs($(SUBDIRS))
