Fixed compilation checks for STK and fixed compilation dependencies of all on tape and client. In more details :   - removed useless HasSTK and CDKDir macro from site.def   - fixed checking for the presence of STK so that it is platform independent   - adapted (simplified) tape/Imakefile

diff --git a/config/Project.tmpl b/config/Project.tmpl
--- a/config/Project.tmpl
+++ b/config/Project.tmpl
@@ -8,8 +8,12 @@ DLFCONF=/var/www/conf/dlf
 
 .PHONY : install clean clobber Makefiles depend checkDESTDIR checkORACLE checkLSF checkGLOBUS checkSTK checkXROOT checkVERSION
 
-all: checkORACLE checkLSF checkGLOBUS checkSTK checkXROOT
+all: checkORACLE checkLSF checkGLOBUS checkXROOT tape client
 	GotoSubdirs($(SUBDIRS))
+
+tape: checkSTK
+
+client:
 
 EXPORTMAN?=$(DESTDIR)/usr/share
 checkDESTDIR:
@@ -45,9 +49,12 @@ checkSTK:
 	@if [ ! -z "${CASTOR_NOSTK}" ]; then \
 	  echo "Compiling without STK support."; \
 	else \
-	  rpm -q stk-ssi-devel >&/dev/null && rpm -q stk-ssi >& /dev/null; \
-	  if [[ $$? -ne 0 ]]; then \
-	    echo "Could not find STK packages. Giving up."; \
+	  if [ ! -e InstallLibDir/CDK/libapi.so -o ! -e InstallLibDir/CDK/libutl.so -o ! -e InstallLibDir/CDK/libipc.so -o ! -e InstallLibDir/CDK/libcl.so ]; then \
+	    echo "Could not find STK libraries. Giving up."; \
+	    exit 1; \
+          fi; \
+	  if [ ! -d /usr/include/CDK ]; then \
+	    echo "Could not find STK development files. Giving up."; \
 	    exit 1; \
           fi; \
 	fi
