Quick test to see why docker build is so slow

diff --git a/continuousintegration/docker/alma9/Dockerfile b/continuousintegration/docker/alma9/Dockerfile
--- a/continuousintegration/docker/alma9/Dockerfile
+++ b/continuousintegration/docker/alma9/Dockerfile
@@ -37,7 +37,6 @@ RUN dnf install -y \
       epel-release \
       jq \
       bc \
-      sqlite \
       krb5-workstation && \
     # logrotate files must be 0644 or 0444
     chmod 0644 /etc/logrotate.d/*
@@ -56,10 +55,11 @@ name=CTA artifacts\n\
 baseurl=file://${CTAREPODIR}\n\
 gpgcheck=0\n\
 enabled=1\n\
-priority=2" > /etc/yum.repos.d/cta-artifacts.repo && \
-    dnf config-manager --enable cta-artifacts && \
-    dnf clean all --enablerepo=\* && \
-    rm -rf /etc/rc.d/rc.local && \
-    # Check that CTA packages are available
-    dnf list available cta-taped > /dev/null 2>&1 || \
-    (echo "cta-taped RPM is missing from the repository" 1>&2; exit 1)
+priority=2" > /etc/yum.repos.d/cta-artifacts.repo
+
+# Quick test to see which one of these is so slow
+RUN dnf config-manager --enable cta-artifacts
+RUN dnf clean all --enablerepo=\*
+RUN rm -rf /etc/rc.d/rc.local
+RUN dnf list available cta-taped > /dev/null 2>&1
+RUN (echo "cta-taped RPM is missing from the repository" 1>&2; exit 1)
