List clang-format issues in job output and remove tag fetching
Closes #973

See merge request cta/CTA!712

Changelog: maintenance
Issue: #973

diff --git a/.gitlab/ci/analysis.gitlab-ci.yml b/.gitlab/ci/analysis.gitlab-ci.yml
--- a/.gitlab/ci/analysis.gitlab-ci.yml
+++ b/.gitlab/ci/analysis.gitlab-ci.yml
@@ -52,15 +52,29 @@ clang-format-report:
     - when: always
   image: $EL9_IMAGE
   script:
-    - yum install -y git-clang-format
+    - yum install -y epel-release
+    - yum install -y git-clang-format bat
     - TARGET_BRANCH=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-$CI_DEFAULT_BRANCH}
-    - git fetch origin $TARGET_BRANCH:$TARGET_BRANCH
+    - git fetch --no-tags origin $TARGET_BRANCH:$TARGET_BRANCH
     - echo "Running clang-format for changes compared to branch $TARGET_BRANCH"
-    - git-clang-format $TARGET_BRANCH HEAD --diff > clang-format.output
+    - git-clang-format $TARGET_BRANCH HEAD --diff > clang-format.diff || true
+    - |
+      if [ $(wc -l < clang-format.diff) -le 1 ]; then
+        echo "No clang-format issues found"
+        exit 0
+      fi
+    - |
+      if [ $(wc -l < clang-format.diff) -le 1000 ]; then
+        bat --style=plain --color=always clang-format.diff
+      else
+        echo "Clang-format output too large. Please check job artifacts"
+      fi
+    - exit 1 # clang-format failed, so the job should fail
   artifacts:
-    when: always
+    when: on_failure
+    expire_in: 7 days
     paths:
-      - clang-format.output
+      - clang-format.diff
 
 clang-format-apply:
   stage: analysis
@@ -82,7 +96,7 @@ clang-format-apply:
   image: $EL9_IMAGE
   variables:
     REPO_REMOTE: https://gitlab-ci-token:${CI_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
-    CLANG_FORMAT_REPORT: clang-format.output
+    CLANG_FORMAT_REPORT: clang-format.diff
   before_script:
     - yum install -y git git-clang-format patch
     - git config user.email $GITLAB_USER_EMAIL
