ensured proper exit

diff --git a/.gitlab/ci/analysis.gitlab-ci.yml b/.gitlab/ci/analysis.gitlab-ci.yml
--- a/.gitlab/ci/analysis.gitlab-ci.yml
+++ b/.gitlab/ci/analysis.gitlab-ci.yml
@@ -58,9 +58,16 @@ clang-format-report:
     - git fetch --no-tags origin $TARGET_BRANCH:$TARGET_BRANCH
     - echo "Running clang-format for changes compared to branch $TARGET_BRANCH"
     - git-clang-format $TARGET_BRANCH HEAD --diff > clang-format.diff || true
+    - |
+      if [ -s clang-format.diff ]; then
+        echo "No clang-format issues found"
+        exit 0
+      fi
     - bat --style=plain --color=always clang-format.diff
+    - exit 1 # clang-format failed, so the job should fail
   artifacts:
-    when: always
+    when: on_failure
+    expire_in: 7 days
     paths:
       - clang-format.diff
 
