Start with yamllint

diff --git a/.gitlab/ci/lint.gitlab-ci.yml b/.gitlab/ci/lint.gitlab-ci.yml
--- a/.gitlab/ci/lint.gitlab-ci.yml
+++ b/.gitlab/ci/lint.gitlab-ci.yml
@@ -3,7 +3,7 @@
 
 lint-cpp:
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
@@ -36,7 +36,7 @@ lint-cpp:
 
 lint-bash:
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
@@ -57,7 +57,7 @@ lint-bash:
 
 lint-python:
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
@@ -76,7 +76,7 @@ lint-python:
 
 lint-licenses:
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
@@ -88,10 +88,11 @@ lint-licenses:
     entrypoint: ["/usr/bin/env"]
   script:
     - python3 continuousintegration/checks/check_gitlab_ci_key_order.py .gitlab/
+    - yamllint .gitlab
 
 lint-licenses:
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
@@ -109,7 +110,7 @@ lint-licenses:
 # And then add a before_script: section that populates this FORMAT_DIFF file
 .format-report:
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
@@ -120,7 +121,7 @@ lint-licenses:
   variables:
     FORMAT_DIFF:
   before_script:
-    - exit 1 # The jobs that extend this job should override this
+    - exit 1  # The jobs that extend this job should override this
   script:
     - |
       if [[ ! -f "$FORMAT_DIFF" ]]; then
@@ -138,7 +139,7 @@ lint-licenses:
       else
         echo "Format diff too large. Please check job artifacts"
       fi
-    - exit 1 # format checks failed, so the job should fail
+    - exit 1  # format checks failed, so the job should fail
   artifacts:
     when: on_failure
     expire_in: 7 days
@@ -201,7 +202,7 @@ format-apply:
 trigger-sonarcloud:
   allow_failure: true
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
       when: manual
@@ -221,7 +222,7 @@ trigger-sonarcloud:
 danger-review:
   interruptible: false
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
       when: always
