[CI] Add yamllint and gitlab ci key order enforcement (cta/CTA!1192)
Closes #1443

diff --git a/.gitlab/ci/lint.gitlab-ci.yml b/.gitlab/ci/lint.gitlab-ci.yml
--- a/.gitlab/ci/lint.gitlab-ci.yml
+++ b/.gitlab/ci/lint.gitlab-ci.yml
@@ -3,16 +3,16 @@
 
 lint-cpp:
   stage: lint
-  image:
-    name: $IMAGE_LINT
-    entrypoint: ["/usr/bin/env"]
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
     - if: $PIPELINE_TYPE != "DEFAULT"
       when: never
     - when: always
-  needs: [] # Ensure no artifacts are downloaded
+  image:
+    name: $IMAGE_LINT
+    entrypoint: ["/usr/bin/env"]
   script:
     - cppcheck --xml
                --force
@@ -36,16 +36,16 @@ lint-cpp:
 
 lint-bash:
   stage: lint
-  image:
-    name: $IMAGE_LINT
-    entrypoint: ["/usr/bin/env"]
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
     - if: $PIPELINE_TYPE != "DEFAULT"
       when: never
     - when: always
-  needs: [] # Ensure no artifacts are downloaded
+  image:
+    name: $IMAGE_LINT
+    entrypoint: ["/usr/bin/env"]
   script:
     - all_shell_scripts=( **/*.sh )
     - if [ ${#all_shell_scripts[@]} -eq 0 ]; then echo "No shell scripts"; exit 0; fi
@@ -57,16 +57,16 @@ lint-bash:
 
 lint-python:
   stage: lint
-  image:
-    name: $IMAGE_LINT
-    entrypoint: ["/usr/bin/env"]
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
     - if: $PIPELINE_TYPE != "DEFAULT"
       when: never
     - when: always
-  needs: [] # Ensure no artifacts are downloaded
+  image:
+    name: $IMAGE_LINT
+    entrypoint: ["/usr/bin/env"]
   script:
     - ruff check --output-format gitlab | tee ruff.json | jq -C
   artifacts:
@@ -74,18 +74,34 @@ lint-python:
     reports:
       codequality: ruff.json
 
-lint-licenses:
+lint-yaml:
   stage: lint
-  image:
-    name: $IMAGE_LICENSE_CHECK
-    entrypoint: [""]
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
     - if: $PIPELINE_TYPE != "DEFAULT"
       when: never
     - when: always
-  dependencies: []
+  image:
+    name: $IMAGE_LINT
+    entrypoint: ["/usr/bin/env"]
+  script:
+    - python3 continuousintegration/checks/check_gitlab_ci_key_order.py .gitlab/
+    - yamllint .
+
+lint-licenses:
+  stage: lint
+  needs: []  # Ensure no artifacts are downloaded
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: never
+    - if: $PIPELINE_TYPE != "DEFAULT"
+      when: never
+    - when: always
+  image:
+    name: $IMAGE_LICENSE_CHECK
+    entrypoint: [""]
   script:
     - reuse lint
 
@@ -94,7 +110,7 @@ lint-licenses:
 # And then add a before_script: section that populates this FORMAT_DIFF file
 .format-report:
   stage: lint
-  needs: [] # Ensure no artifacts are downloaded
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_COMMIT_TAG
       when: never
@@ -105,7 +121,7 @@ lint-licenses:
   variables:
     FORMAT_DIFF:
   before_script:
-    - exit 1 # The jobs that extend this job should override this
+    - exit 1  # The jobs that extend this job should override this
   script:
     - |
       if [[ ! -f "$FORMAT_DIFF" ]]; then
@@ -123,7 +139,7 @@ lint-licenses:
       else
         echo "Format diff too large. Please check job artifacts"
       fi
-    - exit 1 # format checks failed, so the job should fail
+    - exit 1  # format checks failed, so the job should fail
   artifacts:
     when: on_failure
     expire_in: 7 days
@@ -154,11 +170,11 @@ format-report-python:
     - black . --line-length=120 --diff | sed "s|$CI_PROJECT_DIR|$CI_PROJECT_NAME|" > $FORMAT_DIFF
 
 format-apply:
+  allow_failure: true
   stage: lint
   needs:
     - format-report-cpp
     - format-report-python
-  allow_failure: true
   rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
       when: manual
@@ -184,9 +200,9 @@ format-apply:
 
 
 trigger-sonarcloud:
-  stage: lint
-  needs: []
   allow_failure: true
+  stage: lint
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
       when: manual
@@ -206,7 +222,7 @@ trigger-sonarcloud:
 danger-review:
   interruptible: false
   stage: lint
-  needs: []
+  needs: []  # Ensure no artifacts are downloaded
   rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
       when: always
