Rewrite image building in ci

diff --git a/.gitlab/ci/release.gitlab-ci.yml b/.gitlab/ci/release.gitlab-ci.yml
--- a/.gitlab/ci/release.gitlab-ci.yml
+++ b/.gitlab/ci/release.gitlab-ci.yml
@@ -85,6 +85,10 @@ changelog-update:
                                              --description-file changelog_report.md
                                              --verbose
 
+###############################################
+# Publish RPMs
+###############################################
+
 internal-release-cta:
   stage: release
   needs:
@@ -167,3 +171,91 @@ public-release-cta-stable:
                                     --cta-version ${CTA_VERSION}
     - REPO_URL="https://cta-public-repo.web.cern.ch/stable/cta-5/el9/cta/x86_64"
     - ./ci/release/check_rpm_available.sh --repository-url "$REPO_URL" --package "cta-taped" --version "$CTA_VERSION"
+
+
+###############################################
+# Publish Images
+###############################################
+
+.image-targets: &image-targets
+  - cta-taped
+  - cta-rmcd
+  - cta-maintd
+  - cta-frontend
+  - cta-tools
+
+.publish-image:
+  stage: release
+  image:
+    name: $IMAGE_DOCKER_IMAGE_BUILDER
+    entrypoint: [""]
+  variables:
+    CTA_BUILD_ID: ${CI_PIPELINE_ID}git${CI_COMMIT_SHORT_SHA}
+    SRC_IMAGE: ${DOCKER_IMAGE_REGISTRY}/${DOCKER_PRIVATE_REGISTRY_PREFIX}/${TARGET_NAME}:${CTA_BUILD_ID}
+    GIT_SUBMODULE_STRATEGY: none
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: manual
+      allow_failure: true
+  needs:
+    - job: build-images
+      parallel:
+        matrix:
+          - TARGET_NAME: ['$[[ matrix.TARGET_NAME ]]']
+  before_script:
+    - echo "$SOURCE_REGISTRY_PASSWORD" | buildah login \
+        -u "$SOURCE_REGISTRY_USERNAME" \
+        --password-stdin \
+        "$CI_REGISTRY"
+    - echo "$DEST_REGISTRY_PASSWORD" | buildah login \
+        -u "$DEST_REGISTRY_USERNAME" \
+        --password-stdin \
+        "$DEST_REGISTRY"
+  script:
+    - DST_IMAGE="${DEST_REGISTRY}/${DEST_IMAGE_PREFIX}/${TARGET_NAME}:${CI_COMMIT_TAG}"
+    - echo "Publishing ${SRC_IMAGE} -> ${DST_IMAGE}"
+    - buildah pull "$SRC_IMAGE"
+    - buildah tag "$SRC_IMAGE" "$DST_IMAGE"
+    - buildah push "$DST_IMAGE"
+
+publish-images-private:
+  extends: .publish-image
+  parallel:
+    matrix:
+      - TARGET_NAME: *image-targets
+  variables:
+    DEST_REGISTRY: $DOCKER_IMAGE_REGISTRY
+    DEST_IMAGE_PREFIX: $DOCKER_PRIVATE_REGISTRY_PREFIX
+
+    SOURCE_REGISTRY_USERNAME: $DOCKER_LOGIN_USERNAME
+    SOURCE_REGISTRY_PASSWORD: $DOCKER_LOGIN_PASSWORD
+
+    DEST_REGISTRY_USERNAME: $DOCKER_LOGIN_USERNAME
+    DEST_REGISTRY_PASSWORD: $DOCKER_LOGIN_PASSWORD
+
+publish-images-public:
+  extends: .publish-image
+  rules:
+    - if: $ORACLE_SUPPORT == "TRUE"
+      when: never
+    - !reference [.build-cta-image, rules]
+  parallel:
+    matrix:
+      - TARGET_NAME: *image-targets
+  before_script:
+    - |
+      if [[ "$ORACLE_SUPPORT" == "TRUE" ]]; then
+        echo "Oracle-enabled images cannot be published publicly."
+        exit 1
+      fi
+    - !reference [.publish-image, before_script]
+  variables:
+    DEST_REGISTRY: $DOCKER_IMAGE_REGISTRY
+    DEST_IMAGE_PREFIX: $DOCKER_PUBLIC_REGISTRY_PREFIX
+
+    SOURCE_REGISTRY_USERNAME: $DOCKER_LOGIN_USERNAME
+    SOURCE_REGISTRY_PASSWORD: $DOCKER_LOGIN_PASSWORD
+
+    # If this does not work, we may need different credentials for the public registry
+    DEST_REGISTRY_USERNAME: $DOCKER_LOGIN_USERNAME
+    DEST_REGISTRY_PASSWORD: $DOCKER_LOGIN_PASSWORD
