Add versionlock generation from project.json and add multi-platform support

diff --git a/.gitlab/ci/setup.gitlab-ci.yml b/.gitlab/ci/setup.gitlab-ci.yml
--- a/.gitlab/ci/setup.gitlab-ci.yml
+++ b/.gitlab/ci/setup.gitlab-ci.yml
@@ -1,60 +1,53 @@
-# Job to modify the version lock list file for external triggers
-modify-versionlock:
+modify-project-json:
   stage: setup
-  variables:
-    GIT_DEPTH: 0
   rules:
     - if: $PIPELINE_TYPE == "EOS_REGR_AGAINST_CTA_MAIN"
+    # Note that for regressions against a tag, only the EOS image version used in the Helm chart will be updated
     - if: $PIPELINE_TYPE == "EOS_REGR_AGAINST_CTA_TAG"
     - if: $PIPELINE_TYPE == "CTAGENERIC_IMAGE"
   script:
-    - versionlock_path_main="continuousintegration/docker/alma9/etc/yum/pluginconf.d/"
-    - versionlock_file="${versionlock_path_main}versionlock.list"
+    - project_json_file="project.json"
+    # Replace EOS
+    - trimmed_eos_version=$(echo "$CUSTOM_EOS_TAG" | xargs)
     - |
-      if [ -n "${CUSTOM_CTA_TAG}" ]; then
-        versionlock_file=$(./continuousintegration/utils/find_versionlock_list.sh --tag "${CUSTOM_CTA_TAG}")
+      if [ -n "$trimmed_eos_version" ]; then
+        echo "Extracting the currently version locked EOS version from the file..."
+        current_eos_version=$(jq '.platforms.${PLATFORM}.versionlock.eos' $project_json_file)
+        echo "Current EOS version found: $current_eos_version"
+        if [ -n "$current_eos_version" ]; then
+          echo "Replacing $current_eos_version with $CUSTOM_EOS_TAG in the file..."
+          sed -i "s/$current_eos_version/$CUSTOM_EOS_TAG/g" "${project_json_file}"
+        else
+          echo "EOS version not found in the file."
+          exit 1
+        fi
+      else
+        echo "CUSTOM_EOS_TAG is not provided. Skipping EOS version replacement."
       fi
-    - git checkout ${CUSTOM_CTA_TAG} -- "${versionlock_file}"
-    - echo "Extracting the currently version locked EOS version from the file..."
-    - current_eos_version=$(grep -o 'eos-server-[0-9]\+\.[0-9]\+\.[0-9]\+' "${versionlock_file}" | awk -F '-' '{print $3}' | head -1)
-    - echo "Current version found $current_eos_version"
-    - |
-      if [ -z "$current_eos_version" ]; then
-        echo "Version not found! Exiting.";
-        exit 1;
-      fi
-    - echo "Replacing $current_eos_version with $CUSTOM_EOS_TAG in the file..."
-    - sed -i "s/$current_eos_version/$CUSTOM_EOS_TAG/g" ${versionlock_file}
-      # Check if XROOTD_VERSION is provided and not just whitespace
+    # Replace XRootD
+    - sed -i "s/$current_eos_version/$CUSTOM_EOS_TAG/g" ${project_json_file}
     - trimmed_xrootd_version=$(echo "$CUSTOM_XRD_TAG" | xargs)
-      # Check if CUSTOM_XRD_TAG is provided
     - |
       if [ -n "$trimmed_xrootd_version" ]; then
         echo "Extracting the currently version locked XRootD version from the file..."
-        current_xrootd_version=$(grep -o 'xrootd-server-\([0-9]:\)*[0-9]\+\.[0-9]\+\.[0-9]\+' "${versionlock_file}" | awk -F '-' '{print $3}' | head -1)
+        current_xrootd_version=$(jq '.platforms.${PLATFORM}.versionlock.xrootd' $project_json_file)
         echo "Current XRootD version found: $current_xrootd_version"
 
         if [ -n "$current_xrootd_version" ]; then
           echo "Replacing $current_xrootd_version with $CUSTOM_XRD_TAG in the file..."
-          sed -i "s/$current_xrootd_version/$CUSTOM_XRD_TAG/g" "${versionlock_file}"
+          sed -i "s/$current_xrootd_version/$CUSTOM_XRD_TAG/g" "${project_json_file}"
         else
           echo "XRootD version not found in the file."
+          exit 1
         fi
-        # Replace xrootd version in spec file
-        sed -i "s/^%define xrootdVersion $current_xrootd_version/%define xrootdVersion $CUSTOM_XRD_TAG/" cta.spec.in
       else
         echo "CUSTOM_XRD_TAG is not provided. Skipping XRootD version replacement."
       fi
+    # Done
     - echo "File content after replacement"
-    - cat "${versionlock_file}"
-    - |
-      if [ "${versionlock_path_main}versionlock.list" != "${versionlock_file}" ]; then
-        echo "Overwritting versionlock file as tagged version lock file resides in a different path."
-        cp "${versionlock_file}" "${versionlock_path_main}"
-      fi
+    - cat "${project_json_file}"
   artifacts:
     paths:
-      - continuousintegration/docker/alma9/etc/yum/pluginconf.d/versionlock.list
-      - cta.spec.in
+      - project.json
   when: on_success
 
