Add gate job

diff --git a/.gitlab/ci/validate.gitlab-ci.yml b/.gitlab/ci/validate.gitlab-ci.yml
--- a/.gitlab/ci/validate.gitlab-ci.yml
+++ b/.gitlab/ci/validate.gitlab-ci.yml
@@ -56,6 +56,8 @@ validate-project-json:
     - python3 ./continuousintegration/utils/project-json/validate_project_json.py
 
 danger-review:
+  # We allow failure here as we don't want to immediately auto-cancel the entire pipeline
+  # Developers should be allowed to test things without
   allow_failure: true
   image:  registry.cern.ch/docker.io/ruby:3.4-alpine
   stage: validate
@@ -72,3 +74,29 @@ danger-review:
     - gem install faraday-retry
   script:
     - danger --verbose --dangerfile=continuousintegration/danger/Dangerfile --fail-on-errors=true
+    - echo $? > danger_status.txt
+  artifacts:
+    paths:
+      - danger_status.txt
+    expire_in: 1 day
+
+danger-review-gate:
+  stage: validate
+  needs:
+    - job: danger-review
+      artifacts: true
+    - job: test-client
+      optional: true
+    - job: test-client-gfal2
+      optional: true
+    - job: test-repack
+      optional: true
+    - job: test-cta-admin
+      optional: true
+  script:
+    - status=$(cat danger_status.txt)
+    - if [ "$status" -ne 0 ]; then
+        echo "Danger review failed. Please check the merge request comment.";
+        exit 1;
+      fi
+    - echo "Danger passed."
